apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    run: nginx
  namespace:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.12
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
